version: "3.9"
services:
    api:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            MSSQL_SA_PASSWORD: "DummyPassword123"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"