trigger:
- master

resources:
- repo: self

variables:
  tag: $(Build.BuildId)

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: Docker@2
      displayName: Login to Container Registry
      inputs:
        command: login
        containerRegistry: serviceConnection

    - task: Docker@2
      displayName: Build and Push image
      inputs:
        command: buildAndPush
        containerRegistry: serviceConnection
        repository: $(projectId)/paymentGateway

- stage: Deploy
  displayName: Deploy to K8s
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: Bash@3
      displayName: Replace BuildId
      inputs:
        targetType: inline
        script: sed -i s/buildId/$(Build.BuildId)/ k8-deployment.yaml

    - task: Kubernetes@1
      displayName: Delete Deployment
      continueOnError: true
      inputs:
        connectionType: Kubernetes Service Connection
        kubernetesServiceEndpoint: k8sServiceConnection
        command: delete
        useConfigurationFile: true
        configuration: k8-deployment.yaml

    - task: Kubernetes@1
      displayName: Create Deployment
      inputs:
        connectionType: Kubernetes Service Connection
        kubernetesServiceEndpoint: k8sServiceConnection
        command: apply
        useConfigurationFile: true
        configuration: k8-deployment.yaml