apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentGateway
  labels:
    app: paymentGateway
spec:
  replicas: 1
  selector:
    matchLabels:
     app: paymentGateway
  template:
   metadata:
    labels:
     app: paymentGateway
   spec:
    containers:
    - name: paymentGateway
      image: containerRegistryUri/paymentGateway:buildId
      imagePullPolicy: Always
      ports:
        - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: paymentGateway-srv
  labels:
    app: paymentGateway
spec:
  selector:
    app: paymentGateway
  ports:
  - protocol: TCP
    port: 443
    targetPort: 80


---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: paymentGateway-ingress
  labels:
    author: guven-kurt
    template: 3-3-13
    type : api
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/cache-enable: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect : "true"
  namespace: default
spec:
  rules:
  - host: testpaymentgateway.com
    http:
      paths:
      - path: /
        backend:
          serviceName: paymentGateway-srv
          servicePort: 443